import { TStudent } from '../../types/types'

const mockStudents: TStudent[] = [
  {
    id: 1,
    firstName: 'Sebastian',
    lastName: 'Friedli',
    instrument: 'Posaune',
    durationMinutes: 30,
    startOfLesson: '13:00',
    endOfLesson: '13:30',
    dayOfLesson: 'Montag',
    location: 'Musikschule Oberhausen',
    archive: false,
  },
  {
    id: 2,
    firstName: 'Samira',
    lastName: 'Wicky',
    instrument: 'Sousaphon',
    durationMinutes: 40,
    startOfLesson: '13:30',
    endOfLesson: '14:10',
    dayOfLesson: 'Montag',
    location: 'Musikschule Oberhausen',
    archive: false,
  },
  {
    id: 3,
    firstName: 'Xenia',
    lastName: 'Suhner',
    instrument: 'Posaune',
    durationMinutes: 40,
    startOfLesson: '14:10',
    endOfLesson: '14:50',
    dayOfLesson: 'Montag',
    location: 'Musikschule Oberhausen',
    archive: false,
  },
  {
    id: 4,
    firstName: 'Nils',
    lastName: 'Schmied',
    instrument: 'Posaune',
    durationMinutes: 30,
    startOfLesson: '15:00',
    endOfLesson: '15:30',
    dayOfLesson: 'Montag',
    location: 'Musikschule Oberhausen',
    archive: false,
  },

  {
    id: 5,
    firstName: 'Simon',
    lastName: 'Giannoni',
    instrument: 'Sousaphon',
    durationMinutes: 30,
    startOfLesson: '15:00',
    endOfLesson: '15:30',
    dayOfLesson: 'Montag',
    location: 'Musikschule Oberhausen',
    archive: true,
  },
  {
    id: 6,
    firstName: 'Annina',
    lastName: 'Giocca',
    instrument: 'Posaune',
    durationMinutes: 40,
    startOfLesson: '16:15',
    endOfLesson: '16:55',
    dayOfLesson: 'Dienstag',
    location: 'Musikschule Oberhausen',
    archive: false,
  },
  {
    id: 12,
    firstName: 'Josua',
    lastName: 'Anken',
    instrument: 'Sousaphon',
    durationMinutes: 30,
    startOfLesson: '17:00',
    endOfLesson: '17:30',
    dayOfLesson: 'Dienstag',
    location: 'Musikschule Oberhausen',
    archive: false,
  },
  {
    id: 7,
    firstName: 'Henry',
    lastName: 'Mühlematter',
    instrument: 'Posaune',
    durationMinutes: 40,
    startOfLesson: '13:00',
    endOfLesson: '13:40',
    dayOfLesson: 'Mittwoch',
    location: 'Musikschule Niederdorf',
    archive: false,
  },
  {
    id: 8,
    firstName: 'Sandy',
    lastName: 'Wyder',
    instrument: 'Posaune',
    durationMinutes: 30,
    startOfLesson: '13:40',
    endOfLesson: '14:10',
    dayOfLesson: 'Mittwoch',
    location: 'Musikschule Niederdorf',
    archive: false,
  },
  {
    id: 9,
    firstName: 'Xana',
    lastName: 'Berisha',
    instrument: 'Sousaphon',
    durationMinutes: 30,
    startOfLesson: '14:10',
    endOfLesson: '14:40',
    dayOfLesson: 'Mittwoch',
    location: 'Musikschule Niederdorf',
    archive: false,
  },

  {
    id: 10,
    firstName: 'Evelin',
    lastName: 'Kummer',
    instrument: 'Posaune',
    durationMinutes: 30,
    startOfLesson: '15:30',
    endOfLesson: '16:00',
    dayOfLesson: 'Mittwoch',
    location: 'Musikschule Oberhausen',
    archive: false,
  },
  {
    id: 11,
    firstName: 'Samuel',
    lastName: 'Bellinger',
    instrument: 'Posaune',
    durationMinutes: 30,
    startOfLesson: '16:00',
    endOfLesson: '16:30',
    dayOfLesson: 'Mittwoch',
    location: 'Musikschule Oberhausen',
    archive: false,
  },
]

export default mockStudents
