import type { Student } from "../../../types/types"

const mockStudents: Student[] = [
  {
    id: 1,
    firstName: "Sebastian",
    lastName: "Friedli",
    instrument: "Posaune",
    durationMinutes: 30,
    startOfLesson: "13:00",
    endOfLesson: "13:30",
    dayOfLesson: "Montag",
    location: "Musikschule Oberhausen",
    archive: false,
    user_id: "test_user",
  },
  {
    id: 2,
    firstName: "Samira",
    lastName: "Wicky",
    instrument: "Sousaphon",
    durationMinutes: 40,
    startOfLesson: "13:30",
    endOfLesson: "14:10",
    dayOfLesson: "Montag",
    location: "Musikschule Oberhausen",
    archive: false,
    user_id: "test_user",
  },
  {
    id: 3,
    firstName: "Xenia",
    lastName: "Suhner",
    instrument: "Posaune",
    durationMinutes: 40,
    startOfLesson: "14:10",
    endOfLesson: "14:50",
    dayOfLesson: "Montag",
    location: "Musikschule Oberhausen",
    archive: false,
    user_id: "test_user",
  },
  {
    id: 4,
    firstName: "Nils",
    lastName: "Schmied",
    instrument: "Posaune",
    durationMinutes: 30,
    startOfLesson: "15:00",
    endOfLesson: "15:30",
    dayOfLesson: "Montag",
    location: "Musikschule Oberhausen",
    archive: false,
    user_id: "test_user",
  },

  {
    id: 5,
    firstName: "Simon",
    lastName: "Giannoni",
    instrument: "Sousaphon",
    durationMinutes: 30,
    startOfLesson: "15:00",
    endOfLesson: "15:30",
    dayOfLesson: "Montag",
    location: "Musikschule Oberhausen",
    archive: true,
    user_id: "test_user",
  },
  {
    id: 6,
    firstName: "Annina",
    lastName: "Giocca",
    instrument: "Posaune",
    durationMinutes: 40,
    startOfLesson: "16:15",
    endOfLesson: "16:55",
    dayOfLesson: "Dienstag",
    location: "Musikschule Oberhausen",
    archive: false,
    user_id: "test_user",
  },
  {
    id: 12,
    firstName: "Josua",
    lastName: "Anken",
    instrument: "Sousaphon",
    durationMinutes: 30,
    startOfLesson: "17:00",
    endOfLesson: "17:30",
    dayOfLesson: "Dienstag",
    location: "Musikschule Oberhausen",
    archive: false,
    user_id: "test_user",
  },
  {
    id: 7,
    firstName: "Henry",
    lastName: "Mühlematter",
    instrument: "Posaune",
    durationMinutes: 40,
    startOfLesson: "13:00",
    endOfLesson: "13:40",
    dayOfLesson: "Mittwoch",
    location: "Musikschule Niederdorf",
    archive: false,
    user_id: "test_user",
  },
  {
    id: 8,
    firstName: "Sandy",
    lastName: "Wyder",
    instrument: "Posaune",
    durationMinutes: 30,
    startOfLesson: "13:40",
    endOfLesson: "14:10",
    dayOfLesson: "Mittwoch",
    location: "Musikschule Niederdorf",
    archive: false,
    user_id: "test_user",
  },
  {
    id: 9,
    firstName: "Xana",
    lastName: "Berisha",
    instrument: "Sousaphon",
    durationMinutes: 30,
    startOfLesson: "14:10",
    endOfLesson: "14:40",
    dayOfLesson: "Mittwoch",
    location: "Musikschule Niederdorf",
    archive: false,
    user_id: "test_user",
  },

  {
    id: 10,
    firstName: "Evelin",
    lastName: "Kummer",
    instrument: "Posaune",
    durationMinutes: 30,
    startOfLesson: "15:30",
    endOfLesson: "16:00",
    dayOfLesson: "Mittwoch",
    location: "Musikschule Oberhausen",
    archive: false,
    user_id: "test_user",
  },
  {
    id: 11,
    firstName: "Samuel",
    lastName: "Bellinger",
    instrument: "Posaune",
    durationMinutes: 30,
    startOfLesson: "16:00",
    endOfLesson: "16:30",
    dayOfLesson: "Mittwoch",
    location: "Musikschule Oberhausen",
    archive: false,
    user_id: "test_user",
  },
]

export default mockStudents
