import type { Note } from "../../../types/types"

const mockNotes: Note[] = [
  {
    id: 1,
    studentId: 1,
    title: "Semesterziele",
    text: "- Handhaltung verbessern \n - Einführung Vorzeichen \n - Achtel-Rhythmus in langsamem Tempo",
    order: 0,
    user_id: "test_user",
    backgroundColor: null,
  },
  {
    id: 2,
    studentId: 2,
    title: "Semesterziele",
    text: "- Handhaltung verbessern \n - Einführung Vorzeichen \n - Achtel-Rhythmus in langsamem Tempo",
    order: 1,
    user_id: "test_user",
    backgroundColor: null,
  },
  {
    id: 3,
    studentId: 3,
    title: "Semesterziele",
    text: "- Handhaltung verbessern \n - Einführung Vorzeichen \n - Achtel-Rhythmus in langsamem Tempo",
    order: 3,
    user_id: "test_user",
    backgroundColor: null,
  },
  {
    id: 4,
    studentId: 4,
    title: "Semesterziele",
    text: "- Handhaltung verbessern \n - Einführung Vorzeichen \n - Achtel-Rhythmus in langsamem Tempo",
    order: 3,
    user_id: "test_user",
    backgroundColor: null,
  },
  {
    id: 5,
    studentId: 6,
    title: "Semesterziele",
    text: "- Handhaltung verbessern \n - Einführung Vorzeichen \n - Achtel-Rhythmus in langsamem Tempo",
    order: 3,
    user_id: "test_user",
    backgroundColor: null,
  },
  {
    id: 6,
    studentId: 7,
    title: "Semesterziele",
    text: "- Handhaltung verbessern \n - Einführung Vorzeichen \n - Achtel-Rhythmus in langsamem Tempo",
    order: 3,
    user_id: "test_user",
    backgroundColor: null,
  },
  {
    id: 7,
    studentId: 8,
    title: "Semesterziele",
    text: "- Handhaltung verbessern \n - Einführung Vorzeichen \n - Achtel-Rhythmus in langsamem Tempo",
    order: 3,
    user_id: "test_user",
    backgroundColor: null,
  },
  {
    id: 8,
    studentId: 9,
    title: "Semesterziele",
    text: "- Handhaltung verbessern \n - Einführung Vorzeichen \n - Achtel-Rhythmus in langsamem Tempo",
    order: 3,
    user_id: "test_user",
    backgroundColor: null,
  },
  {
    id: 9,
    studentId: 10,
    title: "Semesterziele",
    text: "- Handhaltung verbessern \n - Einführung Vorzeichen \n - Achtel-Rhythmus in langsamem Tempo",
    order: 3,
    user_id: "test_user",
    backgroundColor: null,
  },
  {
    id: 10,
    studentId: 11,
    title: "Semesterziele",
    text: "- Handhaltung verbessern \n - Einführung Vorzeichen \n - Achtel-Rhythmus in langsamem Tempo",
    order: 3,
    user_id: "test_user",
    backgroundColor: null,
  },
  {
    id: 11,
    studentId: 12,
    title: "Semesterziele",
    text: "- Handhaltung verbessern \n - Einführung Vorzeichen \n - Achtel-Rhythmus in langsamem Tempo",
    order: 3,
    user_id: "test_user",
    backgroundColor: null,
  },
]

export default mockNotes
