import type { Student } from '../../../types/types'

const generateMockStudents = (): Student[] => {
  const user_id = 'mock-user-123456' // Single user ID for all students

  return [
    {
      id: 1,
      created_at: new Date(
        new Date().getTime() - 100 * 24 * 60 * 60 * 1000,
      ).toISOString(),
      firstName: 'Lisa',
      lastName: 'Müller',
      instrument: 'Posaune',
      startOfLesson: '16:15',
      endOfLesson: '16:45',
      archive: false,
      location: 'Musikschule, Raum 101',
      user_id: user_id,
      durationMinutes: 30,
      dayOfLesson: 'Montag',
    },
    {
      id: 2,
      created_at: new Date(
        new Date().getTime() - 95 * 24 * 60 * 60 * 1000,
      ).toISOString(),
      firstName: 'Max',
      lastName: 'Schmidt',
      instrument: 'Posaune',
      startOfLesson: '16:45',
      endOfLesson: '17:30',
      archive: false,
      location: 'Musikschule, Raum 101',
      user_id: user_id,
      durationMinutes: 60,
      dayOfLesson: 'Montag',
    },
    {
      id: 3,
      created_at: new Date(
        new Date().getTime() - 90 * 24 * 60 * 60 * 1000,
      ).toISOString(),
      firstName: 'Emma',
      lastName: 'Weber',
      instrument: 'Posaune',
      startOfLesson: '17:40',
      endOfLesson: '18:10',
      archive: false,
      location: 'Musikschule, Raum 101',
      user_id: user_id,
      durationMinutes: 30,
      dayOfLesson: 'Montag',
    },
    {
      id: 4,
      created_at: new Date(
        new Date().getTime() - 85 * 24 * 60 * 60 * 1000,
      ).toISOString(),
      firstName: 'Felix',
      lastName: 'Bauer',
      instrument: 'Posaune',
      startOfLesson: '17:30',
      endOfLesson: '18:15',
      archive: false,
      location: 'Musikschule, Raum 205',
      user_id: user_id,
      durationMinutes: 45,
      dayOfLesson: 'Mittwoch',
    },
    {
      id: 5,
      created_at: new Date(
        new Date().getTime() - 80 * 24 * 60 * 60 * 1000,
      ).toISOString(),
      firstName: 'Sophie',
      lastName: 'Klein',
      instrument: 'Posaune',
      startOfLesson: '18:15',
      endOfLesson: '18:45',
      archive: false,
      location: 'Musikschule, Raum 205',
      user_id: user_id,
      durationMinutes: 30,
      dayOfLesson: 'Mittwoch',
    },
    {
      id: 6,
      created_at: new Date(
        new Date().getTime() - 75 * 24 * 60 * 60 * 1000,
      ).toISOString(),
      firstName: 'Luca',
      lastName: 'Hoffmann',
      instrument: 'Posaune',
      startOfLesson: '14:00',
      endOfLesson: '14:30',
      archive: false,
      location: 'Musikschule, Raum 103',
      user_id: user_id,
      durationMinutes: 30,
      dayOfLesson: 'Freitag',
    },
    {
      id: 7,
      created_at: new Date(
        new Date().getTime() - 70 * 24 * 60 * 60 * 1000,
      ).toISOString(),
      firstName: 'Hannah',
      lastName: 'Schulz',
      instrument: 'Posaune',
      startOfLesson: '14:40',
      endOfLesson: '15:25',
      archive: false,
      location: 'Musikschule, Raum 103',
      user_id: user_id,
      durationMinutes: 45,
      dayOfLesson: 'Freitag',
    },
    {
      id: 8,
      created_at: new Date(
        new Date().getTime() - 65 * 24 * 60 * 60 * 1000,
      ).toISOString(),
      firstName: 'Thomas',
      lastName: 'Wagner',
      instrument: 'Posaune',
      startOfLesson: '10:00',
      endOfLesson: '12:00',
      archive: false,
      location: 'Gemeindehaus, Großer Saal',
      user_id: user_id,
      durationMinutes: 120,
      dayOfLesson: 'Samstag',
    },
    {
      id: 9,
      created_at: new Date(
        new Date().getTime() - 200 * 24 * 60 * 60 * 1000,
      ).toISOString(),
      firstName: 'Julia',
      lastName: 'Fischer',
      instrument: 'Posaune',
      startOfLesson: null,
      endOfLesson: null,
      archive: true, // Archived student
      location: null,
      user_id: user_id,
      durationMinutes: null,
      dayOfLesson: null,
    },
    {
      id: 10,
      created_at: new Date(
        new Date().getTime() - 180 * 24 * 60 * 60 * 1000,
      ).toISOString(),
      firstName: 'Markus',
      lastName: 'Schneider',
      instrument: 'Posaune',
      startOfLesson: null,
      endOfLesson: null,
      archive: true, // Archived student
      location: null,
      user_id: user_id,
      durationMinutes: null,
      dayOfLesson: null,
    },
  ]
}

const mockStudents: Student[] = generateMockStudents()
export default mockStudents
