import type { Note } from '../../../types/types'

const user_id = 'mock-user-123456'
const mockNotes: Array<Note> = [
  {
    user_id,
    id: 1,
    studentId: 1,
    created_at: new Date().toISOString(),
    title: 'Semesterziele',
    text: '<ul><li>Drei neue Akkordfolgen lernen und flüssig spielen können</li><li>Eine komplette Melodie ohne Unterbrechung spielen</li><li>Grundlagen des Fingerpickings beherrschen</li></ul>',
    order: 0,
    backgroundColor: 'green',
  },
  {
    user_id: 'mock-user-123456',
    id: 2,
    studentId: 2,
    created_at: new Date().toISOString(),
    title: 'Semesterziele für Max',
    text: '<ul><li>Erweiterung des Repertoires um drei Rock-Klassiker</li><li>Verbesserung der Techniken für Powerchords und Palm Muting</li><li>Einführung in einfache Gitarrensoli und Improvisation</li></ul>',
    order: 0,
    backgroundColor: 'green',
  },
  {
    user_id: 'mock-user-123456',
    id: 3,
    studentId: 3,
    created_at: new Date().toISOString(),
    title: 'Semesterziele für Emma',
    text: '<ul><li>Erlernen von fünf neuen Akkorden und deren Übergänge</li><li>Einführung in das Fingerpicking auf der Ukulele</li><li>Ein komplettes Lied ohne Unterbrechung spielen können</li></ul>',
    order: 0,
    backgroundColor: 'green',
  },
  {
    user_id: 'mock-user-123456',
    id: 4,
    studentId: 4,
    created_at: new Date().toISOString(),
    title: 'Semesterziele für Felix',
    text: '<ul><li>Verbesserung der Barré-Akkord-Technik</li><li>Erlernen von grundlegenden Rhythmuspatterns</li><li>Einführung in die Notenlehre und das Tabulaturlesen</li></ul>',
    order: 0,
    backgroundColor: 'green',
  },
  {
    user_id: 'mock-user-123456',
    id: 5,
    studentId: 5,
    created_at: new Date().toISOString(),
    title: 'Semesterziele für Sophie',
    text: '<ul><li>Vertiefung der Pentatonik-Skala in verschiedenen Positionen</li><li>Erlernen von Bending-Techniken</li><li>Einführung in die Verwendung von Effektpedale</li></ul>',
    order: 0,
    backgroundColor: 'green',
  },
  {
    user_id: 'mock-user-123456',
    id: 6,
    studentId: 6,
    created_at: new Date().toISOString(),
    title: 'Semesterziele für Luca',
    text: '<ul><li>Verbesserung der Akkordwechsel-Geschwindigkeit</li><li>Einführung in einfache Fingerstyle-Techniken</li><li>Erlernen von drei neuen Melodien</li></ul>',
    order: 0,
    backgroundColor: 'green',
  },
  {
    user_id: 'mock-user-123456',
    id: 7,
    studentId: 7,
    created_at: new Date().toISOString(),
    title: 'Semesterziele für Hannah',
    text: '<ul><li>Erweiterung des Akkordrepertoires um vier neue Akkorde</li><li>Einführung in das Strumming-Pattern für hawaiianische Musik</li><li>Erlernen eines traditionellen hawaiianischen Liedes</li></ul>',
    order: 0,
    backgroundColor: 'green',
  },
  {
    user_id: 'mock-user-123456',
    id: 8,
    studentId: 8,
    created_at: new Date().toISOString(),
    title: 'Semesterziele für Thomas',
    text: '<ul><li>Verbesserung der Alternate Picking Technik</li><li>Einführung in das Spielen von Powerchords</li><li>Erlernen von grundlegenden Rhythmuspatterns für Rock-Musik</li></ul>',
    order: 0,
    backgroundColor: 'green',
  },
  {
    user_id: 'mock-user-123456',
    id: 9,
    studentId: 9,
    created_at: new Date().toISOString(),
    title: 'Letzte Ziele für Julia',
    text: '<ul><li>Wiederholung der erlernten Akkorde und Techniken</li><li>Abschlussprojekt: Aufnahme eines selbst gespielten Liedes</li><li>Tipps für das weitere selbstständige Üben</li></ul>',
    order: 0,
    backgroundColor: 'green',
  },
  {
    user_id: 'mock-user-123456',
    id: 10,
    studentId: 10,
    created_at: new Date().toISOString(),
    title: 'Letzte Ziele für Markus',
    text: '<ul><li>Zusammenfassung der erlernten E-Gitarren-Techniken</li><li>Abschlussprojekt: Improvisation über eine bekannte Akkordfolge</li><li>Empfehlungen für weiterführende Lernressourcen</li></ul>',
    order: 0,
    backgroundColor: 'green',
  },
  {
    user_id: 'mock-user-123456',
    id: 11,
    groupId: 2,
    created_at: new Date().toISOString(),
    title: 'Geplante Konzerte',
    text: '<ul><li>Sommerfest Musikschule</li><li>Herbstmarkt > <b>Zeit noch abklären!</b></li><li>Adventsfeier Altersheim Vitas</li></ul>',
    order: 0,
    backgroundColor: 'yellow',
  },
  {
    user_id: 'mock-user-123456',
    id: 12,
    studentId: 5,
    created_at: new Date().toISOString(),
    title: 'Persönliche Infos',
    text: '<ul><li><b>Musikvorlieben</b>: Klassischer Rock (Led Zeppelin, Pink Floyd), wachsendes Interesse an Indie-Rock</li><li><b>Hobbys</b>: Konzertfotografie, Rudern im Schul-Team</li></ul>',
    order: 1,
    backgroundColor: 'blue',
  },
  {
    user_id: 'mock-user-123456',
    id: 13,
    studentId: 2,
    created_at: new Date().toISOString(),
    title: 'Persönliche Infos',
    text: '<ul><li><b>Musikvorlieben</b>: Heavy Metal und Punk, spielt in einer Schülerband</li><li><b>Hobbys</b>: Skateboarden, Videospiele entwickeln</li></ul>',
    order: 1,
    backgroundColor: 'blue',
  },
  {
    user_id: 'mock-user-123456',
    id: 14,
    studentId: 3,
    created_at: new Date().toISOString(),
    title: 'Persönliche Infos',
    text: '<ul><li><b>Musikvorlieben:</b> Akustische Pop-Musik, singt gerne dazu</li><li><b>Familie:</b> Alleinerziehende Mutter, enger Kontakt zur musikalischen Großmutter</li><li><b>Hobbys:</b> Zeichnen, Teilnahme am Schulchor</li></ul>',
    order: 1,
    backgroundColor: 'blue',
  },
  {
    user_id: 'mock-user-123456',
    id: 15,
    studentId: 4,
    created_at: new Date().toISOString(),
    title: 'Persönliche Infos',
    text: '<ul><li><b>Musikvorlieben:</b> Klassische Gitarrenmusik, Interesse an Flamenco</li><li><b>Schule:</b> 8. Klasse, Leistungskurs Musik, plant Musikstudium</li><li><b>Ziel:</b> An einem Jugend-Gitarrenwettbewerb teilnehmen</li></ul>',
    order: 1,
    backgroundColor: 'blue',
  },
]

export default mockNotes
