name: ⚙️  Deploy API to FTP

on:
  push:
    branches:
      - main # or your default branch name
    paths:
      - "api/**" # This ensures the workflow only runs when changes are made in the api directory

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install Composer dependencies
        run: |
          cd api
          composer install --no-dev --optimize-autoloader

      - name: Create .env file
        run: |
          cd api
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}" >> .env

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_API_SERVER }}
          username: ${{ secrets.FTP_API_USERNAME }}
          password: ${{ secrets.FTP_API_PASSWORD }}
          local-dir: ./api/
