name: Tests
on:
  workflow_dispatch:
    branches:
      - dev
  # push:
  #   branches:
  #     - dev
  # pull_request:
  #   branches:
  #     - main
jobs:
  ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    env:
      STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
    steps:
      - uses: actions/checkout@v3
      - name: Download Stripe CLI
        run: |
          curl -L https://github.com/stripe/stripe-cli/releases/download/v1.13.5/stripe_1.13.5_linux_x86_64.tar.gz --output stripe.tar.gz
          tar -xvf stripe.tar.gz
          sudo mv stripe /usr/local/bin/stripe
      - name: Authenticate Stripe CLI
        run: stripe config set api_key ${{ secrets.STRIPE_SECRET_KEY }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Run subscription tests
        run: npm run pw:subs
