name: Tests
on:
  workflow_dispatch:
    branches:
      - dev
  # push:
  #   branches:
  #     - dev
  # pull_request:
  #   branches:
  #     - main
jobs:
  ui-tests:
    name: UI Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: cat package.json && npm install
      - name: Install Playwright
        run: npx playwright install --with-deps chromium
      - name: Run subscription tests
        run: npm run pw:subs
